"""
Autonomous Fix Loop — rule-based micro-bug auto-repair
======================================================

Scheduled job that runs 3× per day. Detects + fixes specific known
bug patterns in the codebase WITHOUT AI generation:

1. JSONB double-decode (json.loads on already-parsed list/dict)
2. PostgreSQL case folding ("C" quoted → c lowercase)
3. PgConnectionWrapper.cursor() legacy pattern
4. Direct %s placeholder bypassing PgCursorWrapper
5. request.json without silent=True

Each fix is APPLIED MECHANICALLY (regex + AST), not generated by AI.
This eliminates hallucination risk for production code.

After fixes:
- Runs scripts/test_full_radim_journey.py
- If 19/19 PASS → commits to `auto-fix-YYYY-MM-DD` branch + pushes
- If FAIL → reverts via git checkout, logs failure
- Sends SMS/email summary either way

SAFETY RAILS:
- Never edits files in BLOCKED_FILES whitelist (auth, payments, medical)
- Always creates feature branch (never main directly)
- Heroku deploy is MANUAL — user merges PR after review
- Daily budget cap inherited from claude_autonomous_agent
- Cooldown: same fix not applied twice in 24h (anti-loop)
"""

import os
import re
import subprocess
import logging
import json
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)

# ─── Config ────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).parent
TEST_SCRIPT = 'scripts/test_full_radim_journey.py'

# Files NEVER touched by autonomous fixer — too sensitive
BLOCKED_FILES = {
    'auth_routes.py',           # Auth + JWT — security critical
    'auth_middleware.py',
    'gdpr_routes.py',           # Already migrated
    'admin_routes.py',          # Admin endpoints
    'database.py',              # DB adapter — touch and break everything
    'experience_routes.py',     # 70/20 monetization split
    'medical_team.py',          # Medical alerts — critical
    'twilio_voice_routes.py',   # Phone calls
    'twilio_voice_helpers.py',
    'gopay_helpers.py',         # Payments
    'app.py',                   # Main app — too central
    'autonomous_fix_loop.py',   # Don't fix self
}

# Whitelisted file patterns (scoped to common modules where micro-bugs live)
ALLOWED_FILE_PATTERNS = [
    'care_plan.py', 'scaling_optimizations.py',
    'voice_runtime_engine.py', 'circadian_engine.py',
    'anticipation_engine.py', 'brain_core.py',
    'agent_loop.py',
    'memory_helpers.py',
    'communication_needs.py',
    'speech_understanding.py', 'speech_helpers.py',
    'voice_filter.py', 'voice_learning.py',
    'soul_data.py', 'home_assistant.py',
    'kal_routes.py',
    'education_helpers.py',
    'family_link_routes.py', 'family_routes.py',
    'iot_dashboard_routes.py', 'iot_bridge_routes.py',
    'calendar_routes.py',
    'email_inbox_routes.py', 'email_routes.py', 'email_security_routes.py',
    'caregiver_routes.py',
    'predict_routes.py',
    'rhythm_routes.py',
    'survey_routes.py', 'survey_telemetry.py',
    'rtcf_beat.py', 'rtcf_bridge.py',
    'system_status_routes.py',
]

# Cooldown: don't apply same fix-id within 24h (anti-loop)
COOLDOWN_HOURS = 24

# ─── Fix patterns (rule-based, not AI) ─────────────────────────────


def _scan_file(file_path):
    """Read file. Returns (content, lines list) or (None, None) on error."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        return content, content.splitlines()
    except Exception as e:
        logger.warning(f"Can't read {file_path}: {e}")
        return None, None


def _fix_jsonb_double_decode(file_path, content):
    """Pattern: `json.loads(row[N])` without isinstance() guard.

    Heuristic: line contains `json.loads(row[` AND not preceded by
    `isinstance` AND `row[N]` is followed by truthy check `if row[N] else`.
    Replace with isinstance-guarded version.
    """
    fixes_count = 0
    new_content = content

    # Pattern: json.loads(row[X] or '{}')  → with isinstance guard
    # Conservative: only matches simple cases, not complex ternaries
    pattern = re.compile(
        r"json\.loads\(row\[(\d+)\]\s+or\s+'(\[\]|\{\})'\)",
        re.MULTILINE
    )

    def replace(m):
        nonlocal fixes_count
        idx = m.group(1)
        default = m.group(2)
        fixes_count += 1
        default_repr = '[]' if default == '[]' else '{}'
        return (f"(row[{idx}] if isinstance(row[{idx}], (dict, list)) "
                f"else (json.loads(row[{idx}]) if row[{idx}] else {default_repr}))")

    new_content = pattern.sub(replace, content)
    return new_content, fixes_count


def _fix_pg_case_folding(file_path, content):
    """Pattern: SELECT "C" / "E" / "R" / "S" (quoted uppercase columns).
    PG folds unquoted CREATE TABLE identifiers to lowercase. Replace
    with unquoted lowercase.

    SAFETY: only matches single-letter quoted columns C/E/R/S in SELECT
    or INSERT. Never touches other quoted identifiers (table aliases etc).
    """
    fixes_count = 0
    new_content = content

    # SELECT "C", "E", "R", "S" — reorder to lowercase
    # Match pattern: "C"  surrounded by SELECT/comma/space/EOL
    # Conservative — only column-name positions
    for letter in ('C', 'E', 'R', 'S'):
        # SELECT "C", ...
        new_content, count = re.subn(
            rf'SELECT\s+"{letter}"',
            f'SELECT {letter.lower()}',
            new_content
        )
        fixes_count += count

        # , "C",
        new_content, count = re.subn(
            rf',\s*"{letter}"\s*,',
            f', {letter.lower()},',
            new_content
        )
        fixes_count += count

        # , "C" (end of SELECT list, before FROM)
        new_content, count = re.subn(
            rf',\s*"{letter}"\s+FROM',
            f', {letter.lower()} FROM',
            new_content
        )
        fixes_count += count

    return new_content, fixes_count


def _fix_cursor_antipattern(file_path, content):
    """Pattern: `conn = get_connection(); cursor = conn.cursor()`.
    PgConnectionWrapper has no .cursor() — must use db.execute() directly.

    Conservative: only flag for human review (don't auto-fix — too risky
    without context awareness). Returns 0 fixes but logs occurrence.
    """
    if 'conn.cursor()' in content or '.cursor()' in content:
        # Only count, don't fix
        cursor_count = content.count('.cursor()')
        if cursor_count > 0:
            logger.info(f"{file_path}: {cursor_count} .cursor() usages — "
                        "MANUAL FIX REQUIRED (too risky for auto-fix)")
    return content, 0


def _fix_request_json_without_silent(file_path, content):
    """Pattern: `request.json` (without silent=True wrapper).
    Replace with `request.get_json(silent=True)`.

    SAFETY: only inside `if __name__... ` or function bodies, never
    in route decorators / class definitions.
    """
    fixes_count = 0
    new_content = content

    # request.json or {} → request.get_json(silent=True) or {}
    new_content, count = re.subn(
        r'\brequest\.json\b\s+or\s+\{\}',
        'request.get_json(silent=True) or {}',
        new_content
    )
    fixes_count += count

    # data = request.json  (line ending)
    new_content, count = re.subn(
        r'(\s+)data\s*=\s*request\.json\s*$',
        r'\1data = request.get_json(silent=True) or {}',
        new_content,
        flags=re.MULTILINE
    )
    fixes_count += count

    return new_content, fixes_count


# Registry of all fix patterns
FIX_PATTERNS = [
    ('jsonb_double_decode', _fix_jsonb_double_decode),
    ('pg_case_folding', _fix_pg_case_folding),
    ('cursor_antipattern', _fix_cursor_antipattern),
    ('request_json_silent', _fix_request_json_without_silent),
]


# ─── Main loop ─────────────────────────────────────────────────────


def _load_cooldown_state():
    """Track last applied fix per (file, pattern) to prevent re-applying."""
    state_file = REPO_ROOT / '.autonomous_fix_state.json'
    if state_file.exists():
        try:
            with open(state_file) as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def _save_cooldown_state(state):
    state_file = REPO_ROOT / '.autonomous_fix_state.json'
    try:
        with open(state_file, 'w') as f:
            json.dump(state, f, indent=2)
    except Exception as e:
        logger.warning(f"Can't save cooldown state: {e}")


def _can_apply_fix(state, file_path, pattern_id):
    """True if this (file, pattern) combo wasn't fixed in last 24h."""
    key = f"{file_path}::{pattern_id}"
    last_str = state.get(key)
    if not last_str:
        return True
    try:
        last = datetime.fromisoformat(last_str)
        elapsed = datetime.utcnow() - last
        return elapsed > timedelta(hours=COOLDOWN_HOURS)
    except Exception:
        return True


def _mark_applied(state, file_path, pattern_id):
    state[f"{file_path}::{pattern_id}"] = datetime.utcnow().isoformat()


def _run_e2e_test():
    """Run E2E user journey test. Returns (passed, output)."""
    try:
        admin_secret = os.environ.get('ADMIN_SECRET', '')
        env = {**os.environ, 'ADMIN_SECRET': admin_secret}
        result = subprocess.run(
            ['python3', TEST_SCRIPT],
            capture_output=True, text=True, timeout=300,
            cwd=str(REPO_ROOT), env=env,
        )
        # Parse output for "PASSED: N    FAILED: M"
        out = result.stdout + result.stderr
        m = re.search(r'PASSED:\s*(\d+).*?FAILED:\s*(\d+)', out, re.DOTALL)
        if m:
            passed = int(m.group(1))
            failed = int(m.group(2))
            return failed == 0, out
        return False, out
    except subprocess.TimeoutExpired:
        return False, "E2E test TIMED OUT (>300s)"
    except Exception as e:
        return False, f"E2E test error: {e}"


def _git_branch_exists(branch_name):
    try:
        r = subprocess.run(
            ['git', 'show-ref', '--verify', '--quiet', f'refs/heads/{branch_name}'],
            cwd=str(REPO_ROOT)
        )
        return r.returncode == 0
    except Exception:
        return False


def run_autonomous_fix_cycle():
    """Main entry — call this from APScheduler.

    Returns dict with cycle summary.
    """
    started = datetime.utcnow()
    summary = {
        'started_at': started.isoformat(),
        'files_scanned': 0,
        'fixes_attempted': {},  # pattern_id → count
        'fixes_applied': {},
        'e2e_passed': None,
        'committed': False,
        'branch_name': None,
        'error': None,
    }

    state = _load_cooldown_state()

    try:
        # Find all candidate files
        candidates = []
        for pattern in ALLOWED_FILE_PATTERNS:
            file_path = REPO_ROOT / pattern
            if file_path.exists() and pattern not in BLOCKED_FILES:
                candidates.append(file_path)
        summary['files_scanned'] = len(candidates)

        # Apply fixes
        files_changed = []
        for file_path in candidates:
            content, _ = _scan_file(file_path)
            if not content:
                continue

            new_content = content
            file_fixes = {}

            for pattern_id, fix_fn in FIX_PATTERNS:
                if not _can_apply_fix(state, file_path.name, pattern_id):
                    continue
                try:
                    new_content, count = fix_fn(file_path.name, new_content)
                    if count > 0:
                        file_fixes[pattern_id] = count
                        summary['fixes_attempted'][pattern_id] = (
                            summary['fixes_attempted'].get(pattern_id, 0) + count
                        )
                except Exception as e:
                    logger.warning(f"Pattern {pattern_id} failed on {file_path}: {e}")

            # Write if changed
            if new_content != content and file_fixes:
                try:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(new_content)
                    files_changed.append((file_path, file_fixes))
                    for pid in file_fixes:
                        _mark_applied(state, file_path.name, pid)
                    logger.info(f"Auto-fixed {file_path.name}: {file_fixes}")
                except Exception as e:
                    logger.exception(f"Can't write {file_path}: {e}")

        if not files_changed:
            summary['error'] = 'no_fixes_needed'
            _save_cooldown_state(state)
            return summary

        # Run E2E test
        e2e_pass, e2e_output = _run_e2e_test()
        summary['e2e_passed'] = e2e_pass

        if not e2e_pass:
            # Revert all changes
            try:
                subprocess.run(
                    ['git', 'checkout', '--'] + [str(f[0]) for f in files_changed],
                    cwd=str(REPO_ROOT), check=True,
                )
                summary['error'] = 'e2e_failed_reverted'
                logger.warning(f"E2E failed, reverted: {e2e_output[-500:]}")
            except Exception as e:
                summary['error'] = f'e2e_failed_revert_failed: {e}'
            _save_cooldown_state(state)
            return summary

        # Commit to feature branch (never main)
        branch_name = f"auto-fix-{started.strftime('%Y-%m-%d-%H%M')}"
        # Avoid duplicate branch names if rerun
        if _git_branch_exists(branch_name):
            branch_name += '-retry'
        summary['branch_name'] = branch_name

        commit_msg = (
            f"chore: autonomous micro-bug fixes ({started.strftime('%Y-%m-%d %H:%M')})\n\n"
            f"Auto-applied patterns:\n"
            + '\n'.join(f"- {pid}: {cnt}" for pid, cnt in summary['fixes_attempted'].items())
            + f"\n\nE2E: {summary['e2e_passed']} (verified before commit)\n"
            f"Files: {len(files_changed)}\n\n"
            f"Generated by autonomous_fix_loop.py\n"
            f"REVIEW REQUIRED before merging to main."
        )

        try:
            subprocess.run(['git', 'checkout', '-b', branch_name],
                          cwd=str(REPO_ROOT), check=True, capture_output=True)
            subprocess.run(['git', 'add'] + [str(f[0]) for f in files_changed],
                          cwd=str(REPO_ROOT), check=True)
            subprocess.run(['git', 'commit', '-m', commit_msg],
                          cwd=str(REPO_ROOT), check=True, capture_output=True)
            # Push to origin (NOT heroku — don't auto-deploy)
            try:
                subprocess.run(['git', 'push', '-u', 'origin', branch_name],
                              cwd=str(REPO_ROOT), check=True,
                              capture_output=True, timeout=60)
                summary['committed'] = True
            except subprocess.CalledProcessError:
                # No origin remote → just commit locally
                summary['committed'] = 'local_only'
            # Switch back to main
            subprocess.run(['git', 'checkout', 'heroku-deploy-fix'],
                          cwd=str(REPO_ROOT), check=False, capture_output=True)
        except Exception as e:
            summary['error'] = f'commit_failed: {e}'

        _save_cooldown_state(state)

        # Send notification (SMS + email if configured)
        try:
            _send_summary_notification(summary)
        except Exception as e:
            logger.warning(f"Notification failed: {e}")

        return summary

    except Exception as e:
        logger.exception(f"Autonomous fix cycle error: {e}")
        summary['error'] = str(e)[:500]
        _save_cooldown_state(state)
        return summary


def _send_summary_notification(summary):
    """Send summary via SMS + email to maintainer."""
    maintainer_phone = os.environ.get('MAINTAINER_PHONE', '')
    maintainer_email = os.environ.get('MAINTAINER_EMAIL', 'kafanek@kafanek.com')

    fixes_str = ', '.join(
        f"{pid}: {cnt}" for pid, cnt in summary.get('fixes_attempted', {}).items()
    ) or 'none'
    msg = (
        f"🤖 Auto-fix cycle done\n"
        f"Branch: {summary.get('branch_name', 'no_changes')}\n"
        f"Fixes: {fixes_str}\n"
        f"E2E passed: {summary.get('e2e_passed')}\n"
        f"Committed: {summary.get('committed')}\n"
        f"Error: {summary.get('error') or 'none'}\n"
        f"Review on GitHub before merging."
    )

    # SMS via Twilio if configured
    if maintainer_phone:
        try:
            from twilio_voice_helpers import send_sms
            send_sms(maintainer_phone, msg[:300])
        except Exception:
            pass

    logger.info(f"Auto-fix summary: {msg}")
