#!/usr/bin/env python3
"""
🏠 RadimCare Pilot Apartment — unified setup CLI
==================================================
Jeden příkaz: seed Heroku + napsat .env pro mini PC + vypsat hesla.

Použití (interaktivní):
    python scripts/setup_pilot.py

Použití (non-interaktivní):
    python scripts/setup_pilot.py \\
        --senior-email marie@example.cz \\
        --senior-name "Marie Nováková" \\
        --senior-age 82 \\
        --nurse-email eva@radimcare.cz \\
        --nurse-name "Eva Procházková" \\
        --apartment-prefix byt_novakova \\
        --tapo-email iot@radimcare.cz \\
        --tapo-password '...' \\
        --output-env gateway/.env

Závislosti: pouze stdlib (urllib, getpass) — žádné instalace.
"""

import argparse
import getpass
import json
import os
import sys
import urllib.request
import urllib.error


HEROKU_APP = "radim-brain-2025"
HEROKU_API = f"https://radim-brain-2025-be1cd52b04dc.herokuapp.com"


def _post(url, payload, admin_secret):
    """POST JSON s X-Admin-Secret. Vrací (status, body)."""
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(
        url, data=data, method='POST',
        headers={
            'Content-Type': 'application/json',
            'X-Admin-Secret': admin_secret,
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.status, json.loads(resp.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        try:
            return e.code, json.loads(body)
        except Exception:
            return e.code, {'error': body}


def _prompt(label, default=None, secret=False):
    """Interaktivní prompt s defaultem."""
    if default is not None:
        full = f"{label} [{default}]: "
    else:
        full = f"{label}: "
    if secret:
        val = getpass.getpass(full).strip()
    else:
        val = input(full).strip()
    return val or default or ''


def _heroku_admin_secret():
    """Pokus o získání ADMIN_SECRET z Heroku CLI (pokud nainstalovaný)."""
    import subprocess
    try:
        out = subprocess.check_output(
            ['heroku', 'config:get', 'ADMIN_SECRET', '-a', HEROKU_APP],
            stderr=subprocess.DEVNULL,
            timeout=10
        ).decode('utf-8').strip()
        return out if out else None
    except Exception:
        return None


def _write_env(env_path, gateway_env, tapo_email, tapo_password):
    """Zapsat .env soubor pro mini PC gateway."""
    lines = [
        "# ====================================================================",
        "# RadimCare Tapo Gateway — auto-generated by scripts/setup_pilot.py",
        "# Do not commit to git!",
        "# ====================================================================",
        "",
        "# TP-Link Tapo cloud login",
        f"TAPO_EMAIL={tapo_email}",
        f"TAPO_PASSWORD={tapo_password}",
        "",
        "# Heroku Radim backend",
        f"RADIM_API_BASE={gateway_env['RADIM_API_BASE']}",
        f"IOT_GATEWAY_TOKEN={gateway_env['IOT_GATEWAY_TOKEN']}",
        "",
        "# Senior identification (mapování device → user)",
        f"RADIM_SENIOR_ID={gateway_env['RADIM_SENIOR_ID']}",
        f"RADIM_ROOM_PREFIX={gateway_env['RADIM_ROOM_PREFIX']}",
        "",
        f"POLL_INTERVAL_SECONDS={gateway_env['POLL_INTERVAL_SECONDS']}",
        "",
        "# Static IPs zařízení (vyplň po DHCP reservation v routeru)",
        "TAPO_P115_RYCHLOVARKA_IP=",
        "TAPO_P115_MIKROVLNKA_IP=",
        "TAPO_L510E_LOZNICE_IP=",
        "TAPO_H110_IP=",
        "",
    ]
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    os.chmod(env_path, 0o600)


def main():
    ap = argparse.ArgumentParser(description="RadimCare pilot apartment setup")
    ap.add_argument('--senior-email')
    ap.add_argument('--senior-name')
    ap.add_argument('--senior-age', type=int)
    ap.add_argument('--senior-password')
    ap.add_argument('--nurse-email')
    ap.add_argument('--nurse-name')
    ap.add_argument('--nurse-password')
    ap.add_argument('--apartment-prefix')
    ap.add_argument('--apartment-address')
    ap.add_argument('--tapo-email')
    ap.add_argument('--tapo-password')
    ap.add_argument('--output-env', default='gateway/.env')
    ap.add_argument('--admin-secret')
    ap.add_argument('--non-interactive', action='store_true',
                    help='Fail if any required field missing instead of prompting')
    args = ap.parse_args()

    # --- Resolve admin secret ---
    admin_secret = (args.admin_secret
                    or os.environ.get('ADMIN_SECRET')
                    or _heroku_admin_secret())
    if not admin_secret:
        if args.non_interactive:
            print("ERROR: ADMIN_SECRET not provided", file=sys.stderr)
            sys.exit(2)
        admin_secret = _prompt("Admin secret (X-Admin-Secret pro Heroku)", secret=True)
    if not admin_secret:
        print("ERROR: cannot proceed without admin secret", file=sys.stderr)
        sys.exit(2)

    # --- Collect inputs ---
    print("\n🏠 RadimCare Pilot Apartment Setup")
    print("=" * 60)
    print()

    senior_email = args.senior_email or _prompt("Senior email")
    senior_name = args.senior_name or _prompt("Senior jméno (Marie Nováková)")
    senior_age_str = (str(args.senior_age) if args.senior_age else None) or _prompt(
        "Senior věk", default="80")
    senior_age = int(senior_age_str) if senior_age_str.isdigit() else None
    senior_password = args.senior_password or None  # auto-generate if None

    print()
    nurse_email = args.nurse_email or _prompt("Sestra email")
    nurse_name = args.nurse_name or _prompt("Sestra jméno (Eva Procházková)")
    nurse_password = args.nurse_password or None

    print()
    apt_prefix = args.apartment_prefix or _prompt(
        "Apartment prefix (byt_novakova)", default="byt_demo")
    apt_address = args.apartment_address or _prompt(
        "Adresa (volitelné)", default="")

    print()
    tapo_email = args.tapo_email or _prompt(
        "TP-Link Tapo účet email", default="iot@radimcare.cz")
    tapo_password = args.tapo_password or _prompt(
        "TP-Link Tapo heslo", secret=True)

    # --- Build payload ---
    payload = {
        'senior': {
            'email': senior_email, 'name': senior_name, 'age': senior_age,
            'password': senior_password,
        },
        'nurse': {
            'email': nurse_email, 'name': nurse_name,
            'password': nurse_password,
        },
        'apartment': {'prefix': apt_prefix, 'address': apt_address},
    }

    # --- Call Heroku ---
    print()
    print("📡 Kontaktuji Heroku admin endpoint...")
    status, result = _post(f"{HEROKU_API}/api/admin/pilot-setup",
                            payload, admin_secret)
    if status >= 400 or not result.get('success'):
        print(f"\n❌ Setup selhal (HTTP {status}):")
        print(json.dumps(result, indent=2, ensure_ascii=False))
        sys.exit(1)

    # --- Write .env ---
    env_path = args.output_env
    os.makedirs(os.path.dirname(env_path) or '.', exist_ok=True)
    _write_env(env_path, result['gateway_env'], tapo_email, tapo_password)

    # --- Report ---
    print()
    print("✅ Hotovo!")
    print("=" * 60)
    print()
    print(f"SENIOR")
    print(f"  ID:    {result['senior']['id']}")
    print(f"  Email: {result['senior']['email']}")
    print(f"  Jméno: {result['senior']['name']}")
    if result['senior'].get('password_generated'):
        print(f"  HESLO: {result['senior']['password_generated']}  ← USCHOVEJ!")
    else:
        print(f"  Heslo: (existující účet, beze změny)")
    print()
    print(f"SESTRA")
    print(f"  ID:    {result['nurse']['id']}")
    print(f"  Email: {result['nurse']['email']}")
    print(f"  Jméno: {result['nurse']['name']}")
    if result['nurse'].get('password_generated'):
        print(f"  HESLO: {result['nurse']['password_generated']}  ← USCHOVEJ!")
    else:
        print(f"  Heslo: (existující účet, beze změny)")
    print()
    print(f"VAZBA")
    print(f"  link_id: {result['link_id']} (relation=nurse, sos_priority=1)")
    print()
    print(f"IOT ZAŘÍZENÍ")
    print(f"  Pre-registrováno: {result['iot_devices_registered']} kusů")
    print(f"  Status: pending_pairing (gateway je doplní při prvním POSTu)")
    print()
    print(f"GATEWAY .env")
    print(f"  Soubor: {os.path.abspath(env_path)}")
    print(f"  Permissions: 600 (jen owner read/write)")
    print()
    print("=" * 60)
    print("DALŠÍ KROKY:")
    print(f"  1. Zkopíruj {env_path} na mini PC do C:\\RadimCare\\.env")
    print(f"  2. V routeru udělej DHCP reservation pro 4 Wi-Fi zařízení")
    print(f"  3. Doplň IP adresy do .env (TAPO_P115_..._IP, TAPO_L510E_..., TAPO_H110_IP)")
    print(f"  4. Spusť C:\\RadimCare\\tapo_gateway.bat → mrkni do gateway.log")
    print(f"  5. V Tapo app pojmenuj zařízení obsahující 'obyvak', 'kuchyne',")
    print(f"     'loznice', 'chodba' — gateway parsuje pro room mapping")
    print()
    print(f"  Sestra se přihlásí: https://app.radimcare.cz")
    print(f"  Dashboard (jakmile bude live): https://dashboard.radimcare.cz")


if __name__ == '__main__':
    main()
