#!/usr/bin/env python3
"""Test self-diagnostic tools — detect, analyze, source-read, run-test, report."""
import sys, json
sys.path.insert(0, '.')

from claude_autonomous_agent import (
    _tool_detect_app_errors,
    _tool_analyze_self_health,
    _tool_read_source_file,
    _tool_run_diagnostic_test,
    _tool_report_bug,
)

print('=' * 60)
print('SELF-DIAGNOSTIC TOOLS — TEST')
print('=' * 60)
print()

# 1. Detect errors
print('━━━ 1. detect_app_errors(24h) ━━━')
errs = _tool_detect_app_errors(24)
print(f'  has_issues: {errs.get("has_issues")}')
e = errs.get('errors', {})
print(f'  claude_agent_failures: {len(e.get("claude_agent_failures", []))}')
print(f'  crisis_events: {len(e.get("crisis_events", []))}')
print(f'  zero-action runs: {e.get("runs_no_actions", 0)}')
print()

# 2. Self health
print('━━━ 2. analyze_self_health ━━━')
h = _tool_analyze_self_health()
print(f'  health_score: {h.get("health_score")} ({h.get("health_label")})')
metrics = h.get('last_20_runs', {})
print(f'  metrics: failures={metrics.get("failures")}, '
      f'avg_cost=${metrics.get("avg_cost_usd")}, '
      f'avg_duration={metrics.get("avg_duration_s")}s')
warns = h.get('warnings', [])
print(f'  warnings: {len(warns)}')
for w in warns[:3]:
    print(f'    ⚠ {w}')
print()

# 3. Source read — should work
print('━━━ 3. read_source_file (safe) ━━━')
r = _tool_read_source_file('voice_filter.py', start_line=1, num_lines=10)
if r.get('content'):
    print(f'  ✓ {r["file"]}: {r["total_lines"]} lines, showing {r["showing"]}')
    print(f'  preview: {r["content"][:150]}…')
else:
    print(f'  ✗ {r}')
print()

# 4. Source read — blocked patterns
print('━━━ 4. read_source_file (blocked) ━━━')
for path in ['.env', '/etc/passwd', '../../../etc/passwd', 'secret.json',
             'token.txt', 'credentials.json', 'database.exe']:
    r = _tool_read_source_file(path)
    blocked = bool(r.get('error'))
    print(f'  {path:30s} → {"✓ blocked" if blocked else "✗ ALLOWED!!"} ({r.get("error","")[:60]})')
print()

# 5. Run diagnostic test
print('━━━ 5. run_diagnostic_test (subset) ━━━')
# Only run a fast one to keep test quick
r = _tool_run_diagnostic_test('voice_runtime')
print(f'  test=voice_runtime: exit={r.get("exit_code")} success={r.get("success")}')
out = r.get('stdout_tail', '')
if out:
    last_lines = out.splitlines()[-3:]
    for l in last_lines:
        print(f'    | {l}')
print()

# 6. Report bug (test mode — will be cleaned up)
print('━━━ 6. report_bug ━━━')
import time
TAG = f'SELFTEST_{int(time.time())}'
r = _tool_report_bug(
    category='flaky',
    severity='INFO',
    file='scripts/test_claude_self_diagnostic.py',
    description=f'Test bug report {TAG} — auto-generated by self-diagnostic test',
    suggested_fix='No action needed — test artifact'
)
print(f'  reported: {r.get("reported")} | category={r.get("category")} | severity={r.get("severity")}')

# Verify it's in DB
from database import db_context, is_postgres
with db_context() as db:
    if is_postgres():
        row = db.execute(
            "SELECT severity, observation_type, message FROM agent_observations "
            "WHERE message LIKE %s ORDER BY created_at DESC LIMIT 1",
            (f'%{TAG}%',)
        ).fetchone()
    else:
        row = db.execute(
            "SELECT severity, observation_type, message FROM agent_observations "
            "WHERE message LIKE ? ORDER BY created_at DESC LIMIT 1",
            (f'%{TAG}%',)
        ).fetchone()
print(f'  visible in DB: {"✓" if row else "✗"}')
if row:
    vals = row.values() if hasattr(row, 'values') else row
    vals = list(vals)
    print(f'    obs_type={vals[1]} severity={vals[0]}')

# Cleanup
with db_context(commit=True) as db:
    if is_postgres():
        db.execute("DELETE FROM agent_observations WHERE message LIKE %s",
                   (f'%{TAG}%',))
    else:
        db.execute("DELETE FROM agent_observations WHERE message LIKE ?",
                   (f'%{TAG}%',))

# 7. Reject invalid category
print()
print('━━━ 7. report_bug edge cases ━━━')
r = _tool_report_bug('BOGUS', 'INFO', 'x.py', 'test')
print(f'  invalid category rejected: {"✓" if r.get("error") else "✗"}')
r = _tool_report_bug('crash', 'BOGUS', 'x.py', 'test')
print(f'  invalid severity rejected: {"✓" if r.get("error") else "✗"}')

print()
print('=' * 60)
print('DONE')
